### ISSUE TITLE
feat/minor-corrections

### ISSUE THREAD

**Issue by Gerard2par2** [Gerard2par2/life-dashboard#35]
# Tasks
- [x] Tasks buttons size & alignment on vercel
- [x] Tasks deadlines
- [x] Collapse new task form
# Favorites
- [x] Fix open favorite in new tab
# Loader
- [x] Fix svg not displaying on vercel
